import { chromium } from '@playwright/test'
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: 1440, height: 1000 } })
p.on('console', (m) => { if (m.type() === 'error') console.log('CONSOLE ERROR:', m.text()) })
p.on('pageerror', (e) => console.log('PAGE ERROR:', e.message))
await p.goto('http://localhost:5173/', { waitUntil: 'domcontentloaded' })
await p.waitForTimeout(4000)
console.log('cards:', await p.locator('[data-testid=listing-card]').count())
await p.screenshot({ path: '/tmp/shots/home.png' })
const first = p.locator('[data-testid=listing-card]').first()
const href = await first.getAttribute('href')
await first.click()
await p.waitForTimeout(2500)
console.log('detail url:', p.url(), 'from', href)
await p.screenshot({ path: '/tmp/shots/detail.png' })
await b.close()
